### PR TITLE
created DentalCareEpisodeCategory

### PR DESCRIPTION
**Pull request by pacharanero**

### CODE REVIEW

**Comment by pacharanero** [comment]
closes #11

**Comment by davidmiller** [comment]
Do you definitely want this PR to come with nothing in the detail template ? :)

**Comment by pacharanero** [comment]
​Indeed not
​

**Comment by pacharanero** [comment]
OK here's a template to go with the rest of it @davidmiller 
Ugly but functional. Needs a lot of tweaking of the data items to make the data populated view user-friendly

**Pull request merged**
